# This file was generated by GoReleaser. DO NOT EDIT.
cask "li" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "e9dc05bfa5f7db263ed43cc063114a6d8eb36a20fc29456e4b4bce9fb62bfea2"
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "911f36ad7df0cd1173627d4d6cb03475de27f4e1f5482072e1d22391c11ed8b0"
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ed8257db058be5230b32304daa1b542512379698731c20d443314396a886529a"
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "d25a8f5e8c4a32668c0c60f71d51cdf6b9667c274004f7c1e4c433e5ea25e6c8"
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_linux_arm64.tar.gz"
    end
  end

  name "li"
  desc "Free, lightweight LinkedIn CLI over Voyager"
  homepage "https://github.com/oyaah/li"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "li"

  postflight do
    system_command "/usr/bin/xattr", args: ["-cr", "#{staged_path}/li"]
    system_command "/usr/bin/codesign", args: ["--force", "--sign", "-", "#{staged_path}/li"]
  end

  # No zap stanza required

  caveats <<~EOS
    Run `li login` to authenticate with LinkedIn, then `li doctor` to verify the session.
  EOS
end
