# This file was generated by GoReleaser. DO NOT EDIT.
cask "li" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "3d0a4a23012a87b876cde1bc65d3dd72e933948e8db60896e8cb98e987edd4b9"
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5aecbc0b1bc33cfb920631a28ce0dd704497777f5061638abea50c2dfb52cfa1"
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "6f49b0e0ed0043677f6aeadb3d11773c46fbb82a0f77684e190f8a40cd1f2699"
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "f1582725e7d762ea21498a13cfb66670397ef55c4a13865956054a9d4fb489ac"
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_linux_arm64.tar.gz"
    end
  end

  name "li"
  desc "Free, lightweight LinkedIn CLI over Voyager"
  homepage "https://github.com/oyaah/li"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "li"

  postflight do
    system_command "/usr/bin/xattr", args: ["-cr", "#{staged_path}/li"]
    system_command "/usr/bin/codesign", args: ["--force", "--sign", "-", "#{staged_path}/li"]
  end

  # No zap stanza required

  caveats <<~EOS
    Run `li login` to authenticate with LinkedIn, then `li doctor` to verify the session.
  EOS
end
