# This file was generated by GoReleaser. DO NOT EDIT.
cask "li" do
  no_quarantine true

  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "960fe89f73816f82322be29897e6c83b7f3f4dde621820c08df8e8197aff63d8"
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "1f1ceca3eb12d5f5ff611dd06a38abb651510d226dbb8e9606fc3b3dfab98f1b"
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "8ee27e4e09b3f8529ccd29dd42409eecd6f9cd46d9549b97f44d45de092d874e"
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "18ced6bacf05ea483b6ceacb2053daf06b4acf238a76ff89e7cb00d2f0ef5a0d"
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_linux_arm64.tar.gz"
    end
  end

  name "li"
  desc "Free, lightweight LinkedIn CLI over Voyager"
  homepage "https://github.com/oyaah/li"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "li"

  caveats <<~EOS
    Run `li login` to authenticate with LinkedIn, then `li doctor` to verify the session.
  EOS
end
