# This file was generated by li release automation. Do not edit by hand.
class Li < Formula
  desc "Free, lightweight LinkedIn CLI over Voyager"
  homepage "https://github.com/oyaah/li"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_darwin_amd64.tar.gz"
      sha256 "960fe89f73816f82322be29897e6c83b7f3f4dde621820c08df8e8197aff63d8"
    end

    on_arm do
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_darwin_arm64.tar.gz"
      sha256 "1f1ceca3eb12d5f5ff611dd06a38abb651510d226dbb8e9606fc3b3dfab98f1b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_linux_amd64.tar.gz"
      sha256 "8ee27e4e09b3f8529ccd29dd42409eecd6f9cd46d9549b97f44d45de092d874e"
    end

    on_arm do
      url "https://github.com/oyaah/li/releases/download/v#{version}/li_#{version}_linux_arm64.tar.gz"
      sha256 "18ced6bacf05ea483b6ceacb2053daf06b4acf238a76ff89e7cb00d2f0ef5a0d"
    end
  end

  def install
    bin.install "li"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/li version")
  end
end
